### ISSUE TITLE
Doesnt display the complements

### ISSUE THREAD

**Issue by DiegoCastillo2001** [hangorazvan/MagicMirror2#1]
It doesn't display any complements at all

**Comment by hangorazvan** [comment]
check your config.js or where your compliments are for any code typo.
you must put and/or replace in the config.js or compliments.js these lines:

```
		sleepStartTime: 2,
		sleepEndTime: 5,
		morningStartTime: 5,
		morningEndTime: 10,
		noonStartTime: 12,
		noonEndTime: 14,
		afternoonStartTime: 15,
		afternoonEndTime: 18,
		eveningStartTime: 18,
		eveningEndTime: 23,
		nightStartTime: 23,
		nightEndTime: 2,
```

then you must replace in the original compliments.js from line 120 to 132 with these lines:

```
		if (hour >= this.config.sleepStartTime && hour < this.config.sleepEndTime && this.config.compliments.sleep) {
			compliments = this.config.compliments.sleep.slice(0);
		} else if (hour >= this.config.morningStartTime && hour < this.config.morningEndTime && this.config.compliments.morning) {
			compliments = this.config.compliments.morning.slice(0);
		} else if (hour >= this.config.noonStartTime && hour < this.config.noonEndTime && this.config.compliments.noon) {
			compliments = this.config.compliments.noon.slice(0);
		} else if (hour >= this.config.afternoonStartTime && hour < this.config.afternoonEndTime && this.config.compliments.afternoon) {
			compliments = this.config.compliments.afternoon.slice(0);
		} else if (hour >= this.config.eveningStartTime && hour < this.config.eveningEndTime && this.config.compliments.evening) {
			compliments = this.config.compliments.evening.slice(0);
		} else if (hour >= this.config.nightStartTime && hour < this.config.nightEndTime && this.config.compliments.night) {
			compliments = this.config.compliments.night.slice(0);
		}
```

**Comment by DiegoCastillo2001** [comment]
Yeah I did that and it doesn't work

**Comment by hangorazvan** [comment]
paste here your config.js, just compliments section and compliments.js

**Comment by DiegoCastillo2001** [comment]
![2020-06-01 (12)](https://user-images.githubusercontent.com/31832699/83449173-26cbfc00-a421-11ea-9408-d30dc32c7c68.png)

[complents.txt](https://github.com/hangorazvan/MagicMirror2/files/4713190/complents.txt)

**Comment by hangorazvan** [comment]
for me it's OK, be sure that "complents.txt" is named compliments.js, in /modules/default/compliments folder. I supose that txt name is just a typo when you copy.

**Comment by DiegoCastillo2001** [comment]
yeah github doesnt let me upload the .js file

**Comment by hangorazvan** [comment]
just compliments module is not working or anaything else?

**Comment by hangorazvan** [comment]
> yeah github doesnt let me upload the .js file

you just change the extension from .js in .txt or you rename the file?

**Comment by DiegoCastillo2001** [comment]
i just renamed the file

**Comment by hangorazvan** [comment]
> i just renamed the file

OK, so just to e sure, the js file name is compliments.js not "complents.js"

**Comment by DiegoCastillo2001** [comment]
I think is working now, I'll come back to make it go through all the time, to see if it works with all the times
